import type { Metadata } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import dayjs from 'dayjs';
import 'dayjs/locale/ko';
// import '@/styles/globals.css';
import '@/styles/global.css';

const inter = Inter({ subsets: ['latin'] });
dayjs.locale('ko');

export const metadata: Metadata = {
	title: 'Sloth Hell',
	description: "I don't want to go to Sloth Hell",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<html lang="ko">
				<body className={inter.className}>{children}</body>
			</html>
		</>
	);
}
